sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (bullet, enemy) {
    enemy.destroy()
    bullet.destroy()
    info.changeScoreBy(1)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    pewSpeed = dino.vx + 100
    projectile = sprites.createProjectileFromSprite(img`
        . . 6 6 6 6 . . 
        . 6 d 4 4 4 6 . 
        6 1 b 1 1 4 d 6 
        c 1 b b 4 4 1 c 
        . c b b b d c . 
        . . c c c c . . 
        `, dino, pewSpeed, 0)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (dino.isHittingTile(CollisionDirection.Bottom)) {
        dino.vy = -200
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    dino.vx = 35
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    dino.vx = 70
})
info.onLifeZero(function () {
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (player2, enemy) {
    info.changeLifeBy(-1)
    enemy.destroy()
})
let myEnemy: Sprite = null
let projectile: Sprite = null
let pewSpeed = 0
let dino: Sprite = null
info.setLife(3)
scene.setBackgroundColor(5)
tiles.setTilemap(tilemap`level_0`)
scene.setBackgroundImage(projectImages.background_dinoshoot)
dino = sprites.create(img`
    ...........ff........
    ..........ffff.......
    ..........9999999999.
    .........99f999999999
    .........999999999999
    .........999999999999
    .........999999999999
    .........9999999.....
    .........9999999999..
    9.......11111f2......
    9......1111111f......
    99....1111111999.....
    999..9d1111111f9.....
    9999999d111111.......
    9999999d111111.......
    .9999999d11111.......
    ..9999999d111d.......
    ...9999999ddd........
    ....9999999..........
    .....999.99..........
    .....11...1..........
    .....e....e..........
    .....ee...ee.........
    `, SpriteKind.Player)
dino.ay = 500
dino.vx = 40
game.onUpdate(function () {
    scene.centerCameraAt(dino.x + scene.screenWidth() / 2 - 10, 0)
    myEnemy.follow(dino, 50)
})
game.onUpdateInterval(5000, function () {
    myEnemy = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........fffff.........
        ........ff1111bff.......
        .......fb1111111bf......
        .......f111111111f......
        ......fd1111111ffff.....
        ......fd111dd1c111bf....
        ......fb11fcdf1b1bff....
        ......f11111bfbfbff.....
        ......f1b1bdfcffff......
        ......fbfbfcfcccf.......
        ......ffffffffff........
        .........ffffff.........
        .........ffffff.........
        .........fffffff..f.....
        ..........fffffffff.....
        ...........fffffff......
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    myEnemy.x = dino.x + 210
    myEnemy.y = randint(40, 85)
})
